//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmaticAccountingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici_Sayfa_Matrix
    {
        public int ID { get; set; }
        public Nullable<int> Kullanici_ID { get; set; }
        public Nullable<int> Sayfa_ID { get; set; }
    }
}
