//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmaticAccountingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public int ID { get; set; }
        public string FirmaUnvan { get; set; }
        public string KisaAd { get; set; }
        public string VergiNo { get; set; }
        public string VergiDairesi { get; set; }
        public string Adres { get; set; }
        public string YetkiliKisi { get; set; }
        public string TelNo { get; set; }
        public string Mail { get; set; }
        public System.DateTime OlusturulmaTarihi { get; set; }
        public bool INUSE { get; set; }
    }
}
